### ISSUE TITLE
Remove events and clean-up KG after project removal

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#142]
As a Renku owner, I don't want neither Commit Events nor triples of removed projects to be kept.

Things to consider:
* should the Commit Events for the removed projects to be marked with a particular status or simply removed (I guess removing would be better from the performance point of view)?
* should Webhook Service act on event informing about the removal? I guess, yes.
* should Webhook Service/Triples Generator act when found a Commit Event for a removed project? I assume, yes.
* should triples-generator remove eventual datasets being used in the forks? I guess, yes. In the case of an imported dataset, simply remove a relevant dataset's isPartOf.

**Comment by joke1196** [comment]
What would happen if we remove a project with dataset that are forked of modified in other projects? Because removing them would makes us lose the provenance. I would think for the case of Dataset we could invalidate them instead of removing them. So that we could always know where the other datasets in the hierarchy come from.

**Comment by jachro** [comment]
Duplicate
