### ISSUE TITLE
Update events and KG state after project rename

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#166]
As a Renku owner, I'd like graph-services to update the Event Log and the KG after project's title/path change.

Acceptance criteria:
* webhook-service to consume relevant GitLab System Event;
* update `project_path` for all the Commit Events in the Event Log;
* update `project_path` for the access token in the token-repository;
* update the project resources of the Project entity as well as all the places it's referenced in the KG;

---

related to https://github.com/SwissDataScienceCenter/renku-ui/issues/661

**Comment by rokroskar** [comment]
Just to be sure - this only applies when the project path changes, correct? afaik there is a difference between the project name and the project path.

**Comment by jachro** [comment]
Certainly. The issue description updated.

**Comment by pameladelgado** [comment]
Actually, the change of path is not possible from GitLab once there's something in the registry (see below).
![rename-project-error](https://user-images.githubusercontent.com/43743260/68012400-349e8080-fc8a-11e9-8b2f-a33888363f3f.png)
 For now I would say this issue is not a priority and might not even be needed in the future.

**Comment by jachro** [comment]
Done as part of #1033
