### ISSUE TITLE
Check for passwords displayed in logs

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-graph#363]
Some passwords might be displayed in plain text the logs of pods/jobs. If this is the case, these should be redacted.

**Comment by jachro** [comment]
Hi Pamela. Have you maybe noticed something suspicious in renku-graph logs? I was trying to mask them when I go and since some time I haven't seen anything which could make me worried. Do we maybe have a set of info which we don't want to be put into the logs? I guess obvious things are passwords and access tokens but maybe emails should be classified as confidential, too.

**Comment by rokroskar** [comment]
afaik we are not scrubbing emails elsewhere, but we could revisit this
