### ISSUE TITLE
Test out neo4j

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-graph#391]
As a renku-graph owner, I'd like to check if neo4j could be used instead of Jena.

**Acceptance criteria:**
- [x] migrate the provisioning process so it can send data to neo4j (maybe partially);
  - [x] send json-ld payload;
  - [x] send curation updates;
- [x] migrate the dataset free-text search;
- [x] try to hook the renkulab's gitlab and push all the public projects to some dev environment;

- [x] once the above steps are achieved;
  - [x] how difficult the complete migration could be;
  - [x] how efficient is neo4j and how does it fit to our needs;
- [x] do some research how we could achieve our security goals;

**Comment by joke1196** [comment]
The complete migration would quite simple. The way we currently handle updates makes it really easy to add a new index in the whole curation process. Especially if the index can ingestion JSON-LD. 

If we would want to keep the Jena and the Neo4j together it would be quite easy. The only problem with that is that we would not directly use the transactionality offered by Neo4j. In order to do that we would have to change a bit the way the curation process is done (this is not too complex just gathering all the updates and doing them in a transaction).  So we could keep both Jena and Neo4j. Then if we would like to optimize the whole process and use more of the capabilities of Neo4j, a bit more change would be required, for example we could change our model when we query the graph. This would make it difficult to keep Jena and Neo4j in parallel. A this point in my opinion it would be better to go full on Neo4j, and then try to harness all the power of Neo4j by changing the way we query the graph.

**Comment by rokroskar** [comment]
Can any of the curation be offset by making changes to the graph model itself, i.e. in renku-python?
