### ISSUE TITLE
chore: update deprecated github actions

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-graph#472]
Handling of environment variables in GitHub actions has changed due to a security vulnerability - see [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

We should update the CI in all repos to use the new syntax described [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)

**Comment by lorenzo-cavazzi** [comment]
I was about to write that we can close this issue since `renku-graph` is not using `set-env` anywhere.

Anyway, there is one thing I find slightly confusing and that could be addressed here. In the [current "Publish" CI job](https://github.com/SwissDataScienceCenter/renku-graph/blob/master/.github/workflows/test-publish.yml#L84-L101), the `GIT_USER` and `GIT_EMAIL` env variables are explicitly set in the first step but they are not set in the last one, despite they are used in both steps. Everything is working fine because `update-component-version` [sets by default the same values](https://github.com/SwissDataScienceCenter/renku/blob/75bed1d4388e0347789c7945aad413d67706c96f/actions/update-component-version/update-upstream.sh#L18-L19) for those 2 env variables.

I would change the code to either
* set the env variables in a step that preserves them for the whole job (preferred solution, since it's adopted in all the other renku repos. [Here is an example](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/.github/workflows/ci.yml#L74-L77) )
* don't set them at all and use the default values for all the steps
