### ISSUE TITLE
Adopt release strategy similar to other components

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-graph#658]
As already mentioned in personal conversations it would be very nice if the graph-service could adopt a release strategy more similar to the other components. Specifically, this would mean:

- Elevate the "naked" tags to actual releases, including release notes (which can be assembled automatically through [conventional changelog](https://github.com/conventional-changelog/conventional-changelog)), and info about things to watch out for (like database migrations, necessary chart value changes, etc)
- Reduce the frequency of tags/releases a bit. Assume that every tag/release you make will result in a corresponding release of the renku chart (picking up your release notes) and be rolled out to staging and production right away.

Acceptance criteria:
- [x] `test-release.yaml` would have to become simply `test.yaml`;
  - [x] take out the `release` step;
  - [x] remove the release functionality from the `build.sbt` and the `plugins.sbt`;
- [x] create a new issue for the conventional commits machinery to work on graph repo.

**Comment by jachro** [comment]
Thanks @ableuler for creating the issue. Yes, we want to go for the conventional commit. Actually, we do that already to some extent (I mean we try to use the prefixes on all our commits). Probably what's left is to steal from other components some machinery to translating that into some nice release notes.

In regards to the releases, not so sure how we could do fewer releases, though ;) Of course, we can go slower and do less work but perhaps that's not what we're aiming for. So maybe a few words of explanation. When we start working on a new feature or bug, we create a feature branch and work on it up to the stage when the job is fully ready, it's backwards compatible, tested and simply ready to go. So the reasons why I think releasing on every merge is beneficial are:
* the feature/bugfix is complete, we added relevant tests, we tested things manually if that was necessary, we don't want to add anything more; obviously, all the tests pass including our Renku acceptance-tests; (right, we need to add better release notes);
* we don't see more testing can happen after merging; who would be picking up our master to test it? Isn't that responsibility of the acceptance-tests to assure all is good?
* releasing faster means much easier to find out eventual problems -> single change, smaller changeset, easier to nail down eventual problems;
* it's generally hard to decide when to do a release if not after the feature-complete step; should we count the changes to 5 or 10 or do some other algorithm? For us, all the merges are equally good and ready to go;
* we feel complete responsibility for our work and we're doing our best to maintain and monitor our services on PROD all the time; who could know better than us when to do a release?
* I don't see what we could gain from having bigger changesets rolled out to PROD? Is it a problem with the costs of running acceptance-tests or rolling out a version?

**Comment by ableuler** [comment]
> [...]is to steal from other components some machinery to translating that into some nice release notes.

See also https://github.com/SwissDataScienceCenter/sdsc-dev-docs/tree/master/renku-release

I think we have to distinguish between releasing an app/package version and rolling out a piece of software to production. 

### Releases
This is actually the main point of this issue. The purpose of a release in my opinion is to make it easier for the people running a piece of software or using a package in their project to keep track of version changes, have an indication about when they should consider upgrading, and which actions they might have to take when upgrading. While it can admittedly be tricky to figure out which change-set is worthy of a release, simply tagging a release after every PR merge (including trivial fixes, etc) defeats the purpose of a release IMO and just delegates this burden to the user. So if the KG tags a release at every PR merge, we either have to tag a RenkuLab release after every KG release too, or we don't, but then we have simply moved the problem of determining a reasonable set of KG changes worth being released to the Renku repo. Finally, have a look at for example the [GitLab changelog](https://gitlab.com/gitlab-org/gitlab-foss/blob/master/CHANGELOG.md) and imagine how crazy the GitLab version number would evolve if they tagged a release after very merge to master.

### Rollouts
We currently don't do continuous deployment to prod. So when you create a tag on renku-graph, this has no effect on what's running on prod. This means that you do currently not have the control that you would like to have (and that I agree you should have):
> we feel complete responsibility for our work and we're doing our best to maintain and monitor our services on PROD all the time; who could know better than us when to do a release?

As mentioned in the original issue description, one way to actually give you this control would be to:

1. automatically tag a release on RenkuLab whenever one of the components has tagged a release
2. automatically roll out every released RenkuLab version (at least those released from master) to prod  

While this might actually lead to too many releases on the Renku repo, it would make sure that the latest released version of each component runs in production, and thus give more control over prod to the maintainers of the component repos.

> I don't see what we could gain from having bigger changesets rolled out to PROD? Is it a problem with the costs of running acceptance-tests or rolling out a version?

I agree with this point and I see it as a long term goal. However, I do believe that given our current state of testing, we still benefit from not yet rolling out every merged PR on every component immediately, but I'm happy to argue about this. However - and this is my main point - even if we decided that we want to roll out every merged PR to production, this should be achieved by rolling out unreleased versions rather than releasing everything.

**Comment by jachro** [comment]
So, let me try to say a few words but generally, the more I think about the problem, the harder it seems to be :)

Yes, I agree releasing on every merge to master when writing a library could potentially be a problem to some. I can imagine situations when people get annoyed with too many versions to go through when they are about to upgrade. However, from the other side, if the lib is properly versioned (let's say, semantically), I'd be maybe a bit less concerned here. From the other side, I can also think about those annoyed devs waiting for a lib to be released, while the lib authors had a fix and did not release often enough collecting bugfixes people were waiting for.
When it comes to web services, things in my opinion are a bit different. Versions or tags here, are I'd say of less importance. Of course with one crucial point: the services have to be always backwards compatible so they don't break other components. That's more or less what Sam was proposing the other day, that services keep their APIs as long as other components use them. Once all interested parties are switched, the old functionality can be removed. I'd say that gives a lot of freedom to teams and breaks hard dependencies. I think there could be plenty of organisations following such a practice. I'd even risk saying, that the more complex a service/platform is, the more it goes that way. Let's take for instance Amazon or Google, where there are hundreds of services and dozens of teams. If they would all be waiting for each other or synchronising version numbers of their services with other teams, things could get very complicated and slow. So what they do is that no one even knows when teams are deploying new versions. I remember from my previous projects, the communication between teams were mostly on a level of certain functionality API being there on PROD or not, rather than versions. So yes, your point of tagging and releasing is very good, here. Maybe we don't have to release. The only advantage of tagging for me is more human-readable identifiers. Also, a version might be carrying some info, maybe a decision and a level of assurance. That would distinguish all other commit ids from other branches which do not have that label.
The other thing you mentioned is whether we should be releasing everything or just each component. Maybe we should start by tackling this and other problems would become easier (or harder).

**Comment by jachro** [comment]
Actually, there's one more thing about the current way we do releases and rollouts. Because each component keeps changes in its own repository, running acceptance-tests does not give much confidence the changes will work after releasing and bumping the version in the renku requirements.yaml. The reason for that is that because each component does not release, the tests are run against other components that won't be like that after they release. So in other words, let's assume we've got the following situation:
* renku requirements says: UI 1.8, Core 1.1, KG 1.55;
* UI does changes and merges PRs to its repo and each of the change they acceptance-test with /deploy against Core 1.1, KG 1.55;
* Core also does the same and test their changes against UI 1.8, KG 1.55
* On a release of Core and/or UI, it could be surprising that the tests simply start to fail although they were all passing nicely just a few minutes before when run from my repo.

I know it could be a bit radical but if all the components release each feature, eventual problems should be caught much quicker and before they got released.

**Comment by ableuler** [comment]
I'm not questioning semver nor the fact that components should take care not to break each others API, those are all things we agree on.

My main point is plain and simple: Renku is an open source project and RenkuLab is an open source platform. As a person deploying RenkuLab, I expect that the developers publish releases at a reasonable frequency with reasonable release notes. While reasonable is a debatable term here, having several releases per day with release notes being "A whitespace issue was fixed on component X" is not reasonable. 

Therefore, several PR merges of the KG component will be grouped into one release of RenkuLab. It makes more sense for the KG maintainers to do this grouping already at the level of KG releases, rather than delegating this to the maintainers of the Renku repo who do the RenkuLab release.

**Comment by ableuler** [comment]
> * On a release of Core and/or UI, it could be surprising that the tests simply start to fail although they were all passing nicely just a few minutes before when run from my repo.

This would be caught latest by the tests of the PR updating the second dependency on RenkuLab. Also, this would mean that component X was breaking/retiring a previously released but unused API that component Y was actually developing against. I guess no matter how quickly we expose each other to the development happening on the different components, we will always need some a bit of coordination.

> I know it could be a bit radical but if all the components release each feature, eventual problems should be caught much quicker and before they got released.

You could have exactly the same effect from running acceptance tests on the KG not just against the released versions of all the other components but also against the heads of all the components main branches. That's definitely something to consider.

I would actually argue that updating the RenkuLab chart requirements after every PR merge in any of the components (we've been there) encourages pseudo-synchronous development of the components where "you just have to merge 2 PRs at the same time" and don't take proper care of API versioning.

**Comment by jachro** [comment]
Hi @ableuler. I'm sorry, I didn't know it's that important. No worries, we can go that way.

**Comment by ableuler** [comment]
That would be great, thanks! And as ai said, I do understand your arguments for continuously deploying to our production instances and I'm very open for discussing steps taking us in that direction!
