### ISSUE TITLE
Cross-entity search

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-graph#708]
As a Renku user, I'd like to be able to query all main types of entities from a single endpoint.

**NOTE:** This issue is related to the following epic: https://github.com/SwissDataScienceCenter/renku/issues/1924

**Proposal**

**GET /knowledge-graph/entities**

| Query Parameter                     | Description                                                                                    |
|----------------------------|------------------------------------------------------------------------------------------------|
| filterByEntities                 |  List of one or more entities (project,dataset)                            |
| searchIn  ???      | List of fields to search inside (name/title, namespace, user/author, keyword/tag, description, readme |
| filterByVisibility | Restricted vs. public                                                                                      |
| filterByProjectTemplate | python, R, Julia, etc                                                                                      |

We could maybe group the filterBy and inside there do something like:
```
filterBy: {
entity: "project,workflow"
projectTemplate: "R"
}
```

**RESPONSE**

| Field                     | Description                                                                                    |
|----------------------------|------------------------------------------------------------------------------------------------|
| entityType                 |  `project`, `dataset`, `workflow`, etc..                        |
| title    |  Project or dataset title, i.e `My project` |
| name |  Name without spaces i.e `project-name` or `dataset_name`                                                      |
| description |  Dataset or project description (this is in .md format).                                        |
| namespace |  This applies to projects at the moment... `virginiafriedrich` or `renku-qa`                                  |
| creator |  List of creators, this is inside `published` now, it's used in `datasets` maybe for projects we can use the users or group  |
| keywords/tag_list |  Projects have `tag_list` datasets have `keywords` --> we should unify this                            |
| images | List of images for the entity       |
| visibility | We only have this in `project` shall we also use it in datasets/workflows??                                      |
| dateCreated/datePublished |  We want to sort using these dates, in dataset we use only the `dateEdited` now          |
| dateEdited |  We use this in projects `last_activity_at`  |
| links |  We use this in dataset to get extra info for the entity, we don't need it but could be useful |

The response should include also filters and pagination information.

**SINGLE ENTITY RESULTS** ⚠️ ⚠️ ⚠️  (topic for followup design meeting)
- In the case of a project we get a single project when searching and this projects has "versions" inside
- In the case of dataset at the moment we are getting many many results for what we think is a unique dataset with many versions, how can we fix this? We would like to get this grouped and when we click inside a dataset to get versions for it. If we don't fix this now we will have a similar issue with workflows. https://renkulab.io/datasets?q=flights&page=1&orderBy=projectsCount&orderSearchAsc=false
 
 
**TO DISCUSS**
- Clash on keywords/tagList
- Clash on dates --> do we need all this data or we unify this as "last_edited"? this would put entities without edited date always down when sorting per date... unless we create a unified dataset result that puts all versions of a datsaet in a single result.
- Could we get a friendly id for a dataset to put in the URL???
- Is there a clash on creator and user/namespace/group?
- Can we represent visibility on datasets?
 
 
**RESPONSE EXAMPLE (DRAFT)**

```
[  
   {  
      "entityType": "dataset"
      "identifier": "9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c",
      "title":"my dataset",
      "name": "my-dataset",
      "description": "Description of the dataset",  // optional property
      "published": {
        "datePublished": "2012-10-14T03:02:25.639Z", // optional property
        "creator": [
          {
            "name": "e wmtnxmcguz"
          },
          {
            "name": "iilmadw vcxabmh",
            "email": "ticUnrW@cBmrdomoa"             // optional property
          }
        ]
      },
      "date": "2012-10-14T03:02:25.639Z",            // either datePublished or dateCreated
      "projectsCount": 2,
      "keywords": ["grüezi", "kw1", "kw2"],
      "images": ["image.png"],
       "visibility": "dataset visibility" //can we make this happen or not???
      "_links":[  
         {  
            "rel":"details",
            "href":"http://t:5511/datasets/9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c"
         }
      ]
   },
   {  
      "entityType": "project"
      "identifier": "a1b1cb86-c664-4250-a1e3-578a8a22dcbb",
       "title": "project title", //i think in gitlab is name
      "name": "project-name",  //in gitlab is project.path_with_namespace
      "namespace": "project-namespace/with-subgroup"
      "description": "Description of the project"
      "visibility": "project visibility"
      "date": "2012-11-15T10:00:00.000Z",          // last_activity_at (last modified) this can be inside published
      "keywords": ["tag1", "tag2"],                      //this are called tags inside gitlab
      "images": ["https://blah.com/image.png"],
      "_links":[                // this is a link to get info from the project inside the KG... we don't need this at the moment
         {  
            "rel":"details",
            "href":"http://t:5511/project/a1b1cb86-c664-4250-a1e3-578a8a22dcbb"
         }
      ]
   }
]
```

**Comment by jachro** [comment]
After looking at what's there in KG as well as what's considerably easy to do I came up with this proposal of the new endpoint:

#### GET /knowledge-graph/entities

Allows finding `projects`, `datasets`, `workflows`, and `users`.

Filtering:
* `query` - to filter by matching field (e.g., title, keyword, description, etc. as specified below)
* `type` - to filter by entity type; allowed values: `project`, `dataset`, `workflow`, and `user`
* `user` - to filter by user (creator for projects and datasets); the filter would require user's name
* `visibility` - to filter by visibility (restricted vs. public); allowed values: `public`, `internal`, `private`
* `date` - to filter by entity's creation date
* `projectTemplate` no info in KG yet
* ~~group~~ no info in KG yet
* ~~modifyDate~~ no info in KG yet

**NOTE:** at least one filter must be specified

When the `query` parameter is given, the match is done on the following fields:
* entity type
* name/title
* namespace (for the project entity)
* creator (note: workflows has no creator for now)
* keyword/~~tag~~ (keywords for datasets, at the moment we don't have info about project's tags in KG)
* description
* ~~readme~~ (KG does not keep content of README files, yet)

Sorting:
* `score` - to sort by match score (lucene text-matching score, see https://jena.apache.org/documentation/query/text-query.html)
* `name` - to sort by entity name
* `date` - to sort by entity creation date
* ~~by entity modify date~~ (there's no info about modification date in KG)

**NOTE:** the sorting has to be requested by giving the `sort` query parameter with the property name and sorting order (`asc` or `desc`). The default order is ascending so `sort`=`name` means the same as `sort`=`name:asc`.

**Paging:**
* the `page` query parameter is optional and defaults to `1`.
* the `per_page` query parameter is optional and defaults to `20`.

**Response**

| Status                     | Description                                                       |
|----------------------------|-------------------------------------------------------------------|
| OK (200)                   | If there are datasets for the project or `[]` if nothing is found |
| BAD_REQUEST (400)          | If there are no filters or filters with illegal values            |
| INTERNAL SERVER ERROR (500)| Otherwise                                                         |

Response headers:

| Header        | Description                                                                           |
|---------------|---------------------------------------------------------------------------------------|
| `Total`       | The total number of items                                                             |
| `Total-Pages` | The total number of pages                                                             |
| `Per-Page`    | The number of items per page                                                          |
| `Page`        | The index of the current page (starting at 1)                                         |
| `Next-Page`   | The index of the next page (optional)                                                 |
| `Prev-Page`   | The index of the previous page (optional)                                             |
| `Link`        | The set of `prev`/`next`/`first`/`last` link headers (`prev` and `next` are optional) |

Assuming the total is `30` and the URL is `https://renku/knowledge-graph/entities?query=phrase&sort=name:asc&page=2&per_page=10` the following links will be added to the response:

```
Link: <https://renku/knowledge-graph/datasets?query=phrase&sort=name:asc&page=1&per_page=10>; rel="prev"
Link: <https://renku/knowledge-graph/datasets?query=phrase&sort=name:asc&page=3&per_page=10>; rel="next"
Link: <https://renku/knowledge-graph/datasets?query=phrase&sort=name:asc&page=1&per_page=10>; rel="first"
Link: <https://renku/knowledge-graph/datasets?query=phrase&sort=name:asc&page=3&per_page=10>; rel="last"
```

Response body example:

```json
[
  {
    "type": "project",
    "name": "name",
    "namespace": "group/subgroup",
    "visibility": "public",
    "date": "2012-11-15T10:00:00.000Z",
    "creator": "Jan Kowalski",
    "description": "desc",
    "_links": [
      {
        "rel": "details",
        "href": "http://t:5511/projects/group/subgroup/name"
      }
    ]
  },
  {
    "type": "dataset",
    "name": "name",
    "visibility": "public",
    "date": "2012-11-15T10:00:00.000Z", // either datePublished or dateCreated
    "creators": [
      "Jan Kowalski",
      "Zoe"
    ],
    "keywords": [
      "keyword1",
      "keyword2"
    ],
    "description": "desc",
    "_links": [
      {
        "rel": "details",
        "href": "http://t:5511/datasets/122334344"
      }
    ]
  },
  {
    "type": "workflow",
    "name": "name",
    "visibility": "public",
    "keywords": [
      "keyword1",
      "keyword2"
    ],
    "description": "desc",
    "_links": []
  },
  {
    "type": "user",
    "name": "name",
    "_links": []
  }
]
```

**Comment by ciyer** [comment]
This looks like a good start! One question: can we pass in `query='*'`?

**Comment by jachro** [comment]
Hmm, that's a good question. It would more or less mean no `query` parameter. Maybe we can allow this but validate the `perPage` to be <= 100? Would that be ok for you?
