### ISSUE TITLE
provide Dataset information from the graph

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-graph#97]
The graph query endpoint should return information about `Dataset`s on the level of a project as well as for the whole instance.

I added a new query to the `graphql` endpoint so you can find project's data-sets. For each data-set, `id` and `name` could be requested. That's for the good start :)
Query example:
```
dataSets(projectPath: "namespace/project") {
  id
  name        
}
```
More details can be found here:
https://github.com/SwissDataScienceCenter/renku-graph/blob/dataset-info/knowledge-graph/README.md

**Comment by vfried** [comment]
This is what we should receive when we query for a projects dataset, please correct me if i'm wrong on something.

datasets: [
id: string
name: string
description: (i get now an html inside a string and i like it but it could also be a string)
authors: [
 {name:"", 
  email:"", 
  institution:"", 
  id:""
}
]
creator: (string) ==> this is the renku user that created the dataset
files: [
 {name:"", 
  size:"", (if possible)
  id:"",
  date_created:"", 
  date_added:"",
  author:
  creator:
  project: ==> project it first belonged to
 } ]
date_created: (string with date the dataset was created in general)
date_added: (string with the date the dataset was added to renku)
projects: {
 list of projects that imported the same dataset and also project that "owns" the dataset
}
]

**Comment by vfried** [comment]
I think that dataset schema is also for the general search of datasets, the difference in that case is that we want to be able to search for dataset fields, filter them, etc...

**Comment by jachro** [comment]
Thanks for that Virginia! The only question I have is whether all the fields you mentioned is what you want to show according to a relevant UI issue? I'm asking as I'd like this story to be addressing what's really needed and don't want to implement things which might be used in the future. We can always have another story and work on that iteratively. Similarly, in regards to the filters, it'd be great if you could tell me what's needed now.
Thanks

**Comment by vfried** [comment]
At the moment I have as WIP this two prs:

https://github.com/SwissDataScienceCenter/renku-ui/pull/562
https://github.com/SwissDataScienceCenter/renku-ui/pull/555

I'm trying to display dataset info from a specific project. They are reading the data from the datasets yaml files and they should be getting it from the graph. The moment I can get data from the backend I can push them. 

I think it would be usefull that @ciyer check if the fields i think we should be getting are what we really need.

This would be the first thing we need at the moment.

**Comment by jachro** [comment]
Right, it would be great if you @ciyer could verify that.
In terms of the filters, do you think that's something we need from that issue or it would be better to create another one?

**Comment by vfried** [comment]
I think filters should be implemented on a separate issue. The filters are for the dataset search. For this we need to make a new tab where we list all the datasets in renku (like we do with the projects in this tab ==> https://renkulab.io/projects)

**Comment by jachro** [comment]
Good, there's an issue for the datasets search #117 so we should be ok. I'll try to add more details to it.

**Comment by vfried** [comment]
Would it be hard to implement to choose wether we get a list with the full content of the datasets or part of it (like only id and name). I think at the moment the projects don't have so many datasets but it could happen that if the projects have lots of datasets we will have to implement some lazy loading mechanism.

**Comment by jachro** [comment]
Actually, we don't have to do anything as if you'd pass me a query like this:
```
{
  "query": "{ 
    dataSets(projectPath: \"namespace/project\") {
      name 
    } 
  }"
}
```
you'll get:
```
{
  "data": {
    "dataSets": [
      {
        "name" : "x"
      },
      {
        "name" : "xr"
      },
      {
        "name" : "chOorWhraw"
      }
    ]
  }
}
```
So you decide what fields you want the resource to return to you back by listing them in the body of the query.

**Comment by vfried** [comment]
Perfect!

**Comment by ciyer** [comment]
We will need all the dataset metadata fields available in the UI. We want to add the ability to edit metadata soon, and that is a prerequisite for that. We also need information about the project where a dataset was created and where it is imported, since that is the next view we want to implement. I would say that we will need these in the initial version:

```
datasets: [
    id: string
    name: string
    description: string/html
    authors: [{
        name:"",
        email:"",
        institution:"",
        id:""
    }]
    creator: {
        # this is the renku user that created the dataset
        userid: id,
        username: string
    }
    files: [{ 
        name:"",
        size:"", (if possible)
        id:"",
        date_created:"",
        date_added:"",
    }]
    date_created: (string with date the dataset was created in general)
    date_added: (string with the date the dataset was added to renku)
    owner_project: project (the project where this dataset is defined)
    using_projects: [
        # list of projects that import this dataset
    ]
]
```

And these can wait:
```
datasets: [
    files: [{ 
        author:
        creator:
        project: ==> project it first belonged to
        projects: ==> list of projects using the file
    }]
]
```

**Comment by jachro** [comment]
Many thanks @ciyer for all the details.
In regards to the `creator.userid` and `creator.username` would it be fine for you if we use user's email and name, I mean `user@host` and `first-name second-name` for these fields?

**Comment by rokroskar** [comment]
We should stay as close as possible to the definitions from schema.org

**Comment by rokroskar** [comment]
In fact, you shouldn't need to change what you get back from the sparql query apart from stripping the prefix. Ideally we would be returning valid json-ld but that's a separate discussion.

**Comment by jachro** [comment]
Agreed, `json-ld` is probably a separate discussion. My question was more about if UI is happy to use email as `userid` and `first-name second-name` as `username`.

**Comment by rokroskar** [comment]
The UI probably wants gitlab user ID - and this would require us to include gitlab-specific Metadata in the KG, which we haven't done up to this point. Or the graphql backend should make a request to gitlab, but the users endpoint requires an admin token iirc.

**Comment by jachro** [comment]
I can obtain an Access Token for a project from the `token-repository` service and try to use it for fetching GitLab id.

**Comment by ciyer** [comment]
I think the gitlab user ID would be nice to have, since it would make it easy to provide more information about the user in the UI, but I also understand the desire to keep the schema valid. Let us start with the information that is used to identify the user in the schema, and return to the gitlab user later.

**Comment by jachro** [comment]
After pretty long hours spent on both assessing the data available in the Knowledge Graph and possibilities giving by REST and GraphQL, I ended up with two approaches.

1. There are two REST endpoints on the knowledge-graph service returning JSON in HATEOAS format (more on that below):
* `GET /knowledge-graph/projects/:project-path/data-sets`
response example:
```
[  
   {  
      "identifier":"9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c",
      "name":"rmDaYfpehl",
      "_links":[  
         {  
            "rel":"details",
            "href":"http://t:5511/data-sets/9f94add6-6d68-4cf4-91d9-4ba9e6b7dc4c"
         }
      ]
   },
   {  
      "identifier":"a1b1cb86-c664-4250-a1e3-578a8a22dcbb",
      "name":"a",
      "_links":[  
         {  
            "rel":"details",
            "href":"http://t:5511/data-sets/a1b1cb86-c664-4250-a1e3-578a8a22dcbb"
         }
      ]
   }
]
```
* `GET /knowledge-graph/data-sets/:id`
response example:
```
{
  "_links" : [
    {
      "rel" : "self",
      "href" : "https://zemdgsw:9540/data-sets/6f622603-2129-4058-ad29-3ff927481461"
    }
  ],
  "identifier" : "6f622603-2129-4058-ad29-3ff927481461",
  "name" : "data-set name",
  "description" : "vbnqyyjmbiBQpubavGpxlconuqj",  // optional property
  "created" : {
    "dateCreated" : "1970-05-12T06:06:41.448Z",
    "agent" : {
      "email" : "n@ulQdsXl",
      "name" : "v imzn"
    }
  },
  "published" : {
    "datePublished" : "2012-10-14T03:02:25.639Z", // optional property
    "creator" : [
      {
        "name" : "e wmtnxmcguz"
      },
      {
        "name" : "iilmadw vcxabmh",
        "email" : "ticUnrW@cBmrdomoa"             // optional property
      }
    ]
  },
  "hasPart" : [
    {
      "name" : "o",
      "atLocation" : "data/dataset-name/file1",
      "dateCreated" : "1970-05-11T09:08:19.742Z"
    },
    {
      "name" : "rldzpwo",
      "atLocation" : "data/dataset-name/file2",
      "dateCreated" : "1970-01-31T00:45:58.577Z"
    }
  ],
  "isPartOf" : [
    {
      "name" : "namespace1/project1-name"
    },
    {
      "name" : "namespace2/project2-name"
    }
  ]
}
```
The beauty of the HATEOAS approach is that with every response you receive some follow-up links for different scenarios. So for instance in the case of the endpoints listed above, all you need to do is to fetch the initial data (project's data-sets in our case) and you get back a list of simple `id` and `name` items along with a complete link to data-set's details. So you get that link and use it as is to fetch the details. It's also very good from the API providers, as they can change the endpoints and the links and clients won't even notice there was a change in the API. The reasons I added these REST endpoints and I think they should be used over GraphQL (really) are:
* Complexity - our data model becomes more and more complex and using the HATEOAS approach with the links seems to me to be easier to add/change/maintain. You can imagine that e.g. the project's data-sets resource response type is already pretty complex and if you add for instance projects', creators' and agent's details, it could easily become a monster. On the contrary, with the links, initially, you just get the bare minimum and you fetch what you need and when you need.
* More single responsibility resources - in short, project's data-sets resource returns just project's data-sets and not users, project and other details. It should be so much easier to maintain such resources.
* There's a need of every (or almost every) entity in our KG to be a valid URL resource. What that means, e.g. if you get a data-set or user or project entity from KG, it should be identified by this unique url resource which you can simply take and call to get info about it. Because of that, we need REST endpoints to make it work anyway.
* Performance - I realized that GraphQL queries returning complex data structures could be quite tricky to write so they perform well. The reason is quite obvious as to gather various pieces of information, they have to reach multiple sources and I can easily envisage cases where supposedly single HTTP call can in overall perform worse form our user point of view than few quick calls.
* A minor one - no POSTs but GETs to fetch data which seems to be more natural, at least to me.

2. The GraphQL endpoint
query:
```
{
  "query": "{ 
    dataSets(projectPath: \"namespace/project\") {
      identifier!
      name!
      description
      created! {
        dateCreated! 
        agent { 
          email!
          name!
        }
      }
      published {
        datePublished
        creator {
          name!
          email
        }
      }
      hasPart {
        name!
        atLocation!
        dateCreated!
      }
      isPartOf {
        name!
      }
    } 
  }"
}
```
response example:
```
{
  "data": {
    "dataSets": [
      {
        "identifier": "e1fc7b62-e021-434b-9264-dda336bddd4f",
        "name": "data-set name",
        "description": "Data-set long description",
        "created": {
          "dateCreated": "1981-09-05T10:38:29.457Z",
          "agent": {
            "email": "user1@host",
            "name": "user 1"
          }
        },
        "published": {
          "datePublished": "2019-07-30",
          "creator": []
        },
        "hasPart": [],
        "isPartOf": [{
          "name": "namespace/project"
        }]
      },
      {
        "identifier": "5b7a1394-93b5-4e75-932d-e041cf46349d",
        "name": "xr",
        "description": null,
        "created": {
          "dateCreated": "1991-09-05T10:38:29.457Z",
          "agent": {
            "email": "user2@host",
            "name": "user 2"
          }
        },
        "published": {
          "datePublished": null,
          "creator": [{
            "name": "author1 name",
            "email": null
          }]
        },
        "hasPart": [{
          "name": "file1",
          "atLocation"": "data/data-set-name/file1",
          "dateCreated": "1991-09-05T10:38:29.457Z"
        }],
        "isPartOf": [{
          "name": "namespace/project"
        }]
      },
      {
        "identifier": "b1aa58af-a488-4bae-97b4-d6d349f98412",
        "name": "chOorWhraw",
        "description": null,
        "created": {
          "dateCreated": "2001-09-05T10:38:29.457Z",
          "agent": {
            "email": "user3@host",
            "name": "user 3"
          }
        },
        "published": {
          "datePublished": "2001-09-05T10:38:29.457Z",
          "creator": [{
            "name": "author1 name",
            "email": "author1@mail.org"
          }, {
            "name": "author2 name",
            "email": "author2@mail.org"
          }]
        },
        "hasPart": [{
          "name": "file1",  
          "atLocation"": "data/chOorWhraw-name/file1",
          "dateCreated": "2001-09-05T10:38:29.457Z"
        }, {
          "name": "file2"  
          "atLocation"": "data/chOorWhraw-name/file2",
          "dateCreated": "2001-09-05T10:48:29.457Z"
        }],
        "isPartOf": [{
          "name": "namespace/project1"
        }, {
          "name": "namespace/project2"
        }]
      }
    ]
  }
}
```

**NOTES/ASSUMPTIONS**
* I imagine you can find some of the property names a bit not very precise or misleading. This is because we tried to keep the `schema.org` and `prov` schemas so we don't have to do mental mapping and we can start serving `json-ld` responses at some point.
* We cannot serve some of the properties mentioned in the comments as we simply don't have the data in our KG. We can think what's essential and I can try to enrich the responses by querying other sources like GitLab. I'll do that anyway for things like users and projects anyway so UI and other clients have a consistent, single API.

**Comment by ciyer** [comment]
Small, but important comment -- please use "dataset(s)" as the term for this entity. I myself prefer the spelling with a space, but we have standardized around dataset (one word) in Renku, so we should stick to that.

More substantial comments to come.

**Comment by rokroskar** [comment]
What I like about the HATEOAS approach is that it can leverage the fact that we have a linked-data graph. You wouldn't even need to return e.g. info about the creator - you could just return ids. The other thing that is nice about the REST response above is that all that is needed to turn it into a json-ld object is the inclusion of the `@context` at the top. Then any of our clients who are designed to work with json-ld can easily use this data as well. 

Just one thing I noticed - you have:

```
"created" : {
    "dateCreated" : "1970-05-12T06:06:41.448Z",
    "agent" : {
      "email" : "n@ulQdsXl",
      "name" : "v imzn"
    }
  },
  "published" : {
    "datePublished" : "2012-10-14T03:02:25.639Z", // optional property
    "creator" : [
      {
        "name" : "e wmtnxmcguz"
      },
      {
        "name" : "iilmadw vcxabmh",
        "email" : "ticUnrW@cBmrdomoa"             // optional property
      }
    ]
  },
```

The `agent` under `dateCreated` should be under a list of `creator` - that's how we handle/represent creator(s) elsewhere (e.g. like you have under `published`)

**Comment by ciyer** [comment]
Sorry for the delay. I wrote up a response, but I must have forgotten to push the comment button.

I agree with all of your points in favor of the REST approach, but my concern, and the reason GraphQL is appealing, is that it allows for more efficient communication between the UI and backend. This becomes more important as the amount of metadata per entity increases.

On the UI, we will show an overview page for datasets, were we just want a small amount of information (name, author, description, creation date). Consider a project with 5 datasets. for this project, we will need to make 6 calls to the server (one to get the list of datasets and 5 to get the other information), discarding most of the information that is returned.

With the REST-only solution, how do we plan on optimizing the responses and client/server communication?

**Comment by jachro** [comment]
I see your point. What we can maybe do is to go for a kind of middle ground and agree what's the set of properties you would need when querying for the list of project's data-sets? In other words,  I'd return you all name, author name, description and creation date for each data-set along with the links. So you get a complete set of data for a single page and then you follow the links when you need. I'm aware this solution would make us more coupled but as long as you would need just a reasonable small subset of the properties, we still should be better in the terms of performance and maybe in the future some other users of the API could take advantage of that.

The whole KG API is I think a bit of an experiment at this point anyway, as I guess we're not really sure what kind of data we'll need (at least I don't know). I'm just getting worried after the data-set endpoint, that the data model we'd be returning from the GraphQL endpoints will either grow too big or we'll end up with many resources which the clients would have to know about while with the HATEOAS they could simply follow just by reading the responses.

**Comment by ciyer** [comment]
I think we can start with the REST endpoint, since it will make sense to have that anyway. We can revisit GraphQL in the future.

**Comment by jachro** [comment]
Yes, of course. I'll leave the GraphQL resources for the time being anyway.

In terms of the `GET /knowledge-graph/projects/:project-path/datasets` endpoint. Are you fine with having just the `name`, `identifier` and link to the details for each dataset for now?

**Comment by ciyer** [comment]
Let us do it that way. 

It means that we will have to fetch datasets and all of the details for the first page of datasets, which is not optimal for the UI, but I think it is the best tradeoff because it does not make sense for the `datasets` endpoint to provide all the information we actually need.
